# Generated by Django 4.1 on 2022-08-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(upload_to='media/arquivos'),
        ),
    ]
