# Generated by Django 4.1 on 2022-08-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0002_alter_relatorio_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo',
            field=models.FileField(upload_to='arquivos'),
        ),
    ]
